### ISSUE TITLE
Backpressure edge cases

### ISSUE THREAD

**Issue by nichoth** [nichoth/pull-combine-latest#3]
Pushable source streams buffer their data if the consumer is not ready for it. If we combine 2 infinite event streams, one of them emitting constantly and the other one never emitting an event, then the first stream would keep buffering forever b/c we only drain it after we have gotten an even from all input streams.

**Comment by ahdinosaur** [comment]
my understanding is that a read of the combined stream calls each read of every individual stream once, but only emits when they all have returned something at least once. so each individual stream is only read as many times as the source stream is read.

in your example case, it would be fine if the infinite event stream properly handled it's back pressure (like `pull.infinite`), but you're right that a `pull-pushable` source would keep buffering forever (which is why `pull-pushable` is usually a bad idea if it isn't being immediately drained). so all this is to say i'm not sure if we should change this module to work with a source having improper back-pressure.
